openapi: "3.0.1"
info:
  title: "photo-app-users-api-cognito-stack"
  version: "1.0"
servers:
- url: "https://okkmi5svxb.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "Prod"
paths:
  /login:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:339713074675:function:photo-app-users-api-cogni-LoginUserHandlerFunction-PpUR83PiC7PZ/invocations"
        passthroughBehavior: "when_no_match"
  /users:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:339713074675:function:photo-app-users-api-cogni-CreateUserHandlerFunctio-yesRm8vhwke1/invocations"
        passthroughBehavior: "when_no_match"
  /users/me:
    get:
      parameters:
      - name: "AccessToken"
        in: "header"
        required: true
        schema:
          type: "string"
      security:
      - PhotoAppUsersApiAuthorizer: []
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:339713074675:function:photo-app-users-api-cognito-GetUserHandlerFunction-WOahwL04FnlD/invocations"
        passthroughBehavior: "when_no_match"
  /confirm:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:339713074675:function:photo-app-users-api-cogni-ConfirmUserHandlerFuncti-XXvoWNcmTEhL/invocations"
        passthroughBehavior: "when_no_match"
  /users/{userName}/add-to-group:
    post:
      parameters:
      - name: "userName"
        in: "path"
        required: true
        schema:
          type: "string"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:339713074675:function:photo-app-users-api-cogni-AddUserToGroupHandlerFun-hYI4t3EljTdw/invocations"
        passthroughBehavior: "when_no_match"
components:
  securitySchemes:
    PhotoAppUsersApiAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        type: "cognito_user_pools"
        providerARNs:
        - "arn:aws:cognito-idp:us-east-1:339713074675:userpool/us-east-1_MPBwjerxA"
x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false
